FROM nginx:alpine

# Install python3, pip3 and poetry
RUN apk add --no-cache python3
RUN apk add --no-cache py3-pip
RUN apk add --no-cache poetry

# Copy necessary files
COPY pyproject.toml ./
#COPY poetry.lock ./
COPY databaseManager ./databaseManager
COPY API.py ./API.py
COPY routers ./routers 
COPY scripts/linux/startServer.sh /startServer.sh
COPY database/EmptyDatabase.db ./Database.db
COPY database/EmptyDatabase.db ./ProductionDatabase.db
COPY database/TestDatabase.db ./TestDatabase.db

# build poetry enviroment
#RUN poetry install --no-root

EXPOSE 8000

# Start command
CMD ["/startServer.sh"]

